name: mini_sales_dash
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  provider: 6.1.5
  go_router: 15.2.0
  http: ^1.1.0

flutter:
  uses-material-design: true
